name: mus_law
description: "Music player app to listen to your favorite tunes"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  mqtt_client: ^10.11.1
  connectivity_plus: ^5.0.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
